version: "3.7"

services: 

    nginx: 
        image: nginx:latest
        restart: always
        ports:
            - 80:80
        volumes: 
            - "./nginx/conf.d:/etc/nginx/conf.d"
            
    dauphinois:
        build: ./server
        image: dauphinois:latest
        ports:
            - 3000:3000

    client: 
        build: ./client
        image: client:latest
        ports:
            - 8080:8080
            
volumes: 
    dbdata:
    