version: "3.7"

services: 
    mongo:
        image: mongo
        restart: always
        volumes: 
            - "dbdata:/data/db"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
            MONGO_INITDB_DATABASE: ${DB_NAME}
    
    dauphinois:
        build: ./server
        image: dauphinois:latest
        ports:
            - 3000:3000
volumes: 
    dbdata:
    