version: "3.7"

services: 

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
    
    dauphinois:
        build: 
            context: ./server
            dockerfile: Dockerfile-dev
        image: dauphinois:latest
        ports:
            - 3000:3000
        volumes:
            - "./server:/usr/src/app"
        